# Generated by Django 5.1.2 on 2025-01-26 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_apki', '0003_alter_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
